### ISSUE TITLE
clarificaton on a1

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs585/main#1]
Hi professor,
Can you please clarify on these:
a)run_fsa
description of input_symbols:
input_symbols...list of strings representing the input string
I am assuming input symbols as a list of characters. Also in the test case it is taken as  list of characters by converting one single string. Is it list of strings?

b) get_productions corner case
In the doc string of Tree class, children can be empty. Suppose we define Tree as Tree(“S”), in this case, there are no children, then by assuming RHS of the production rule can be empty and considered as valid, I am considering output as [('S',[])]. Is this correct?

**Comment by aronwc** [comment]
>
> a)run_fsa
> description of input_symbols:
> input_symbols...list of strings representing the input string
> I am assuming input symbols as a list of characters. Also in the test case
> it is taken as list of characters by converting one single string. Is it
> list of strings?


Yes, input_symbols is a list of strings. In `test_baa_fsa`, each string is
a single character; in `test_name_fsa`, each string is a name.

b) get_productions corner case
> In the doc string of Tree class, children can be empty. Suppose we define
> Tree as Tree(“S”), in this case, there are no children, then by assuming
> RHS of the production rule can be empty and considered as valid, I am
> considering output as [('S',[])]. Is this correct?


In that case, the output should be the empty list `[]`, since there are no
actual productions in that grammar (technically, it's an ill-defined
grammar).

Similarly, in the `test_get_productions` example, there is no production
with a leaf on the LHS (e.g., there is no production ('flight', [])).

Best,
Aron

**Comment by ranjeetkumar** [comment]
Thanks professor,
One more confusion, I am getting in is_valid_production method

If this is rule:
rules = [('S', ['NP', 'VP']),
                 ('NP', ['ProperNoun']),
                 ('ProperNoun', ['John', 'Mary', 'Arnab']),
                 ('VP', ['V', 'ProperNoun']),
                 ('V', ['likes', 'hates'])]
In part-of-speech rule such as 'ProperNoun', ['John', 'Mary','Arnab'], 
is production ( 'ProperNoun', ['John', 'Mary','Arnab']) or  ( 'ProperNoun', ['John', 'Mary'])  considered as valid? I am condering those as invalid assuming productions comming from part of speech rule have RHS of lenght 1.

**Comment by aronwc** [comment]
Those should be invalid. POS should indeed have a RHS of length 1.
-Aron

**Comment by ranjeetkumar** [comment]
Thanks a lot.
