### ISSUE TITLE
What is the "n_params" in evaluate_combinations?

### ISSUE THREAD

**Issue by AngeloK** [iit-cs585/main#10]
Just got confused about what "n_params" exactly is. Can anyone explain it? 
Thanks

**Comment by Sihan0616** [comment]
What 'n_params' do you mean? Where is it?

**Comment by AngeloK** [comment]
In Log.txt, the output of function "evaluate_combinations":
<img width="579" alt="screen shot 2017-03-18 at 8 25 51 pm" src="https://cloud.githubusercontent.com/assets/1455943/24077378/92d4aa12-0c19-11e7-93ed-aba3fb0093be.png">

**Comment by Sihan0616** [comment]
That should be the total number of parameters to be used for this classifier. You could see when caps, pos, chunk and context are all TRUE value, you will use the most parameters.

**Comment by thirumalrao** [comment]
@LarryZhao0616  - isn't 18290 in X shape the number of features ? If that's the case, then for different combinations, it will only be lower than that.

**Comment by AngeloK** [comment]
Problem solved [here](https://github.com/iit-cs585/assignments/issues/21)

**Comment by dporunne** [comment]
Can you give an example for n_params?
I still did not understand, what we mean by 'parameters used by classifier' !!!

**Comment by aronwc** [comment]
If clf is the classifier, then clf.coef_ is the matrix of parameters. n_params is the number of entries in this matrix.
