### ISSUE TITLE
A1 Valid Production

### ISSUE THREAD

**Issue by kprakash2** [iit-cs585/main#3]
rules = [('S', ['NP', 'VP']),
                 ('NP', ['ProperNoun']),
                 ('ProperNoun', ['John', 'Mary']),
                 ('VP', ['V', 'ProperNoun']),
                 ('V', ['likes', 'hates'])]
if rules are specified as above will the following be considered as valid production or not 
1.('S', ['NP'])
2.('S', ['VP'])

**Comment by prateekagrawal06** [comment]
No, It won't be considered as a production.

Thanks,
Prateek Agrawal

**Comment by kprakash2** [comment]
Thanks.
