### ISSUE TITLE
Does anyone have problem installing math module on python 3.5.2 & 3.6?

### ISSUE THREAD

**Issue by thirumalrao** [iit-cs585/main#5]
I tried installing math module on version 3.5.2, it failed. Upgraded python to 3.6, am still getting the following error - 
$pip3 install math
Collecting Math
  Downloading Math-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-yoomnugu/Math/setup.py", line 2, in <module>
        raise RuntimeError("Package 'Math' must not be downloaded from pypi")
    RuntimeError: Package 'Math' must not be downloaded from pipit

**Comment by aronwc** [comment]
No need to install. It comes with python.

**Comment by thirumalrao** [comment]
Strange, IDE is still complaining there is no module named math, but yes, I was able to use the module. Thanks !

**Comment by VarunBanka** [comment]
> I tried installing math module on version 3.5.2, it failed. Upgraded python to 3.6, am still getting the following error - $pip3 install math Collecting Math Downloading Math-0.5.tar.gz Complete output from command python setup.py egg_info: Traceback (most recent call last): File "", line 1, in File "/private/tmp/pip-build-yoomnugu/Math/setup.py", line 2, in raise RuntimeError("Package 'Math' must not be downloaded from pypi") RuntimeError: Package 'Math' must not be downloaded from pipit

bcs of wrong command, the correct command is
pip install python-math

**Comment by Aryansah10** [comment]
THANKS!!
